version: '3.8'
services:
  elasticsearch:
    container_name: elastic-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=secretkey
    # configs:
    #   - source: elastic_config
    #     target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 20s
        timeout: 10s
        retries: 5
  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:7.0.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    # configs:
    #   - source: kibana_config
    #     target: /usr/share/kibana/config/kibana.yml
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    healthcheck:
      test: curl -X GET localhost:5601 >/dev/null || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
  logstash:
    container_name: logstash-container
    image: docker.elastic.co/logstash/logstash:7.0.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    # configs:
    #   - source: logstash_config
    #     target: /usr/share/logstash/config/logstash.yml
    volumes:
      - logstash-data:/usr/share/logstash/data
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - 5044:5044
      - 5000:5000/tcp
      - 5000:5000/udp
      - 9600:9600
    healthcheck:
      test: curl -X GET localhost:5044 >/dev/null || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
volumes:
  es-data:
  kibana-data:
  logstash-data:
networks:
  elastic:
    driver: bridge
#configs:
#   elastic_config:
#     file: ./elasticsearch.yml
#   logstash_config:
#     file: ./logstash.yml
#   kibana_config:
#     file: ./kibana.yml