
env: 
    tf_actions_working_dir: 'terraform'
  
name: 'Terraform'

on:
  push:
    tags:
      - v*.*.*
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.tf_actions_working_dir }}
        
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
     - name: select workspace
       run: terraform workspace select dev 
       
     - name: Terraform Format
       id: fmt
       run: terraform fmt -check -recursive 
     
     - name: Terraform Init 
       run: terraform init 
    
     - name: Terraform Validate
       id: validate
       run: terraform validate -no-color
    
     - name: Terraform Plan
       id: plan
       run: terraform plan  -no-color
       continue-on-error: true
  
     - name: Terraform Apply
       run: terraform apply -auto-approve
      